-- Insert Boom Warehouse Inventory
-- This migration populates the database with actual products from Boom Warehouse

-- Insert categories first
INSERT INTO categories (id, name, slug, description, is_active) VALUES
('54a5a2ff-95ee-42ff-afa1-57328f0ab039', 'Computers & Electronics', 'computers-electronics', 'Desktop computers, iMacs, and electronic devices', true),
('a35bb4be-4061-4e39-983a-c43271562955', 'Appliances', 'appliances', 'Refrigerators, kitchen appliances, and home appliances', true),
('91972698-cd74-4f96-981a-d37113c525d2', 'Electronics', 'electronics', 'TVs, projectors, speakers, and electronic accessories', true),
('b4f2e8a1-6c93-4d8e-b1a5-7e9f3c2d1b4a', 'Home & Garden', 'home-garden', 'China sets, mirrors, home decor, and garden items', true),
('c5d3f9b2-7e94-5f9e-c2b6-8f0a4d3e2c5b', 'Sports & Recreation', 'sports-recreation', 'Sports equipment and recreational items', true),
('d6e4g0c3-8fa5-6g0f-d3c7-9g1b5e4f3d6c', 'General Merchandise', 'general-merchandise', 'Miscellaneous items and general products', true)
ON CONFLICT (slug) DO NOTHING;

-- Insert products
INSERT INTO products (
    id, name, description, category, condition, sku, price, compare_at_price,
    brand, model, year, quantity, images, specifications, dimensions, weight,
    location, warranty_months, tags, is_active, is_featured
) VALUES
-- Featured High-End iMacs
(
    'imac-2020-27',
    'Apple iMac 27" 2020',
    'Excellent quality Apple iMac 27" 2020 from Apple, powered by Intel i5 3.3GHz with 32GB RAM and 2TB storage. Perfect for professional work and creative projects.',
    'Computers & Electronics',
    'Grade A',
    'BW-APP-IMAC-2020-001',
    420.00,
    1299.99,
    'Apple',
    'iMac',
    2020,
    1,
    '{"/images/products/420_apple_imac_27_2020_intel_i533ghz_32gb_ram_2tb.jpg"}',
    '{"screen_size": "27 inches", "processor": "Intel i5 3.3GHz", "ram": "32GB RAM", "storage": "2TB", "year": 2020}',
    '{"width": 25.6, "height": 20.3, "depth": 8.0}',
    20.5,
    'Warehouse A-1',
    6,
    '{"apple", "imac", "desktop", "professional", "year-2020"}',
    true,
    true
),
(
    'imac-2019-27',
    'Apple iMac 27" 2019 Intel i9',
    'Premium Apple iMac 27" 2019 featuring Intel i9 3.6GHz processor with 32GB RAM and 1TB storage. Perfect for demanding creative and professional work.',
    'Computers & Electronics',
    'Grade A',
    'BW-APP-IMAC-2019-002',
    349.00,
    1799.99,
    'Apple',
    'iMac',
    2019,
    1,
    '{"/images/products/349_apple_imac_27_2019_intel_i9_36ghz_32gb_ram_1tb.jpg"}',
    '{"screen_size": "27 inches", "processor": "Intel i9 3.6GHz", "ram": "32GB RAM", "storage": "1TB", "year": 2019}',
    '{"width": 25.6, "height": 20.3, "depth": 8.0}',
    20.5,
    'Warehouse A-1',
    6,
    '{"apple", "imac", "desktop", "professional", "year-2019", "i9"}',
    true,
    true
),

-- Dell Desktop
(
    'dell-desktop-i7',
    'Dell Desktop Computer i7 16GB 1TB Win 11',
    'Reliable Dell desktop computer with Intel i7 processor, 16GB RAM, and 1TB storage. Comes with Windows 11 installed and ready to use.',
    'Computers & Electronics',
    'Grade B',
    'BW-DEL-DESK-003',
    159.00,
    449.99,
    'Dell',
    'Desktop',
    2019,
    1,
    '{"/images/products/159_dell_desktop_computer_i716gb_1tb_win_11_dell_2.jpg"}',
    '{"processor": "Intel i7", "ram": "16GB RAM", "storage": "1TB", "operating_system": "Windows 11"}',
    null,
    null,
    'Warehouse A-1',
    3,
    '{"dell", "desktop", "windows-11", "i7"}',
    true,
    true
),

-- Large Appliances - Featured
(
    'frigidaire-gallery-32cf',
    'Frigidaire Gallery 32 Cu Ft Refrigerator',
    'Premium Frigidaire Gallery 32 cubic foot stainless steel refrigerator. Large capacity perfect for families with modern features and energy efficiency.',
    'Appliances',
    'Grade A',
    'BW-FRI-REF-004',
    790.00,
    2499.99,
    'Frigidaire',
    'Gallery',
    null,
    1,
    '{"/images/products/7900_new_frigidaire_gallery_32_cu_ft_refrigerator.jpg"}',
    '{"capacity": "32 cu ft", "finish": "Stainless Steel"}',
    '{"width": 36.0, "height": 70.0, "depth": 32.0}',
    300.0,
    'Warehouse B-1',
    12,
    '{"frigidaire", "refrigerator", "stainless-steel", "large-capacity"}',
    true,
    true
),

-- Large TV
(
    'sharp-60-aquos-tv',
    'Sharp 60" Aquos LED TV',
    'Large Sharp 60-inch Aquos LED TV with excellent picture quality. Perfect for home entertainment and large living rooms.',
    'Electronics',
    'Grade B',
    'BW-SHA-TV-005',
    249.00,
    799.99,
    'Sharp',
    'Aquos LED TV',
    null,
    1,
    '{"/images/products/24900_pre-owned_60_sharp_aquos_led_tv_model_lc-60l.jpg"}',
    '{"screen_size": "60 inches", "display_type": "LED"}',
    null,
    null,
    'Warehouse A-2',
    3,
    '{"sharp", "tv", "led", "60-inch"}',
    true,
    true
),

-- More Budget iMacs
(
    'imac-2015',
    'Apple iMac 27" 2015',
    'Reliable Apple iMac 27" 2015 with Intel i5 processor. Great for general computing and light creative work.',
    'Computers & Electronics',
    'Grade B',
    'BW-APP-IMAC-2015-009',
    199.00,
    899.99,
    'Apple',
    'iMac',
    2015,
    1,
    '{"/images/products/19900_pre-owned_apple_imac_27_screen_2015_intel_i5.jpg"}',
    '{"screen_size": "27 inches", "processor": "Intel i5", "year": 2015}',
    '{"width": 25.6, "height": 20.3, "depth": 8.0}',
    20.5,
    'Warehouse A-1',
    3,
    '{"apple", "imac", "desktop", "year-2015"}',
    true,
    false
),

(
    'imac-2013',
    'Apple iMac 27" 2013',
    'Classic Apple iMac 27" 2013 with Intel i5 processor. Great budget option for basic computing needs.',
    'Computers & Electronics',
    'Grade C',
    'BW-APP-IMAC-2013-015',
    190.00,
    599.99,
    'Apple',
    'iMac',
    2013,
    1,
    '{"/images/products/19000_pre-owned_apple_imac_27_screen_2013_intel_i5.jpg"}',
    '{"screen_size": "27 inches", "processor": "Intel i5", "year": 2013}',
    '{"width": 25.6, "height": 20.3, "depth": 8.0}',
    20.5,
    'Warehouse A-1',
    1,
    '{"apple", "imac", "desktop", "year-2013", "budget"}',
    true,
    false
),

-- Refrigerators
(
    'frigidaire-75cf',
    'Frigidaire 7.5 Cu Ft Refrigerator',
    'Compact Frigidaire 7.5 cubic foot refrigerator with freezer. Perfect for apartments, offices, or small spaces.',
    'Appliances',
    'Grade A',
    'BW-FRI-REF-010',
    149.00,
    399.99,
    'Frigidaire',
    null,
    null,
    1,
    '{"/images/products/149_frigidaire_75cf_refrigerator_freezer_55x21x21.jpg"}',
    '{"capacity": "7.5 cu ft"}',
    '{"width": 21.0, "height": 55.0, "depth": 21.0}',
    100.0,
    'Warehouse B-1',
    6,
    '{"frigidaire", "refrigerator", "compact"}',
    true,
    false
),

(
    'frigidaire-mini',
    'Frigidaire 1.6 Cu Ft Mini Refrigerator',
    'Stylish retro Frigidaire 1.6 cubic foot mini refrigerator. Perfect for dorms, offices, or personal use.',
    'Appliances',
    'Grade A',
    'BW-FRI-MINI-011',
    69.00,
    199.99,
    'Frigidaire',
    null,
    null,
    1,
    '{"/images/products/6900_frigidaire_16_cu_ft_mini_refrigerator_retro_s.jpg"}',
    '{"capacity": "1.6 cu ft", "style": "Retro"}',
    '{"width": 17.7, "height": 19.4, "depth": 18.6}',
    40.0,
    'Warehouse B-2',
    3,
    '{"frigidaire", "mini-fridge", "retro", "compact"}',
    true,
    false
),

-- Projectors
(
    'hitachi-projector',
    'Hitachi CP-WX625 3LCD Projector',
    'Professional Hitachi CP-WX625 3LCD projector delivering 4000 lumens. Perfect for business presentations and home theater.',
    'Electronics',
    'Grade C',
    'BW-HIT-PROJ-006',
    75.00,
    299.99,
    'Hitachi',
    'CP-WX625',
    null,
    1,
    '{"/images/products/75_hitachi_cp-wx625_3lcd_projector_4000_lumens_hd.jpg"}',
    '{"lumens": "4000 lumens", "technology": "3LCD"}',
    null,
    null,
    'Warehouse A-3',
    3,
    '{"hitachi", "projector", "3lcd", "professional"}',
    true,
    false
),

(
    'christie-projector',
    'Christie LW400 LCD Projector',
    'High-quality Christie LW400 LCD projector for professional presentations and home theater use.',
    'Electronics',
    'Grade C',
    'BW-CHR-PROJ-007',
    99.00,
    399.99,
    'Christie',
    'LW400',
    null,
    1,
    '{"/images/products/99_christie_lw400_lcd_projector_boomwarehouse_4554.jpg"}',
    '{"technology": "LCD"}',
    null,
    null,
    'Warehouse A-3',
    3,
    '{"christie", "projector", "lcd", "professional"}',
    true,
    false
),

-- Home & Garden Items
(
    'excel-china-set',
    'Excel Fine China Set',
    'Beautiful Excel fine china set in excellent condition. Perfect for special occasions and elegant dining.',
    'Home & Garden',
    'Grade B',
    'BW-EXC-CHI-012',
    199.00,
    499.99,
    'Excel',
    null,
    null,
    1,
    '{"/images/products/199_excel_fine_china_set_boomwarehouse_4554_renais.jpg"}',
    '{}',
    null,
    null,
    'Warehouse C-1',
    1,
    '{"excel", "china", "dinnerware", "elegant"}',
    true,
    false
),

(
    'mikasa-china-set',
    'Mikasa Blair Fine China Set',
    'Elegant Mikasa Blair fine china set in like new condition. Beautiful addition to any dining collection.',
    'Home & Garden',
    'Grade A',
    'BW-MIK-CHI-013',
    250.00,
    699.99,
    'Mikasa',
    'Blair',
    null,
    1,
    '{"/images/products/250_mikasablair_fine_china_set_like_new_boomwareho.jpg"}',
    '{}',
    null,
    null,
    'Warehouse C-1',
    3,
    '{"mikasa", "china", "dinnerware", "like-new"}',
    true,
    false
),

-- Kitchen Appliances
(
    'frigidaire-cooking-plate',
    'Frigidaire 2-in-1 Cooking Plate/Pizza Maker',
    'Versatile Frigidaire 2-in-1 cooking plate and pizza maker. Perfect for quick meals and entertaining.',
    'Appliances',
    'Grade A',
    'BW-FRI-COO-014',
    35.00,
    89.99,
    'Frigidaire',
    null,
    null,
    1,
    '{"/images/products/35_frigidaire_2_in_1_cooking_platepizza_maker_boom.jpg"}',
    '{"type": "2-in-1 Cooking Plate/Pizza Maker"}',
    null,
    null,
    'Warehouse B-3',
    3,
    '{"frigidaire", "cooking", "pizza-maker", "kitchen"}',
    true,
    false
)

ON CONFLICT (sku) DO NOTHING;

-- Add inventory transactions for initial stock
INSERT INTO inventory_transactions (product_id, type, quantity, reason, notes)
SELECT id, 'incoming', quantity, 'Initial inventory', 'Boom Warehouse opening inventory'
FROM products
WHERE created_at = (SELECT MAX(created_at) FROM products);